export default [
    {
        name: 'GRID_SIZE',
        label: 'Grid Size',
        type: 'vector2',
        defaultValue: [200, 200],
    },
    {
        name: 'START_NODE_NUM',
        label: 'Starting # of Nodes',
        type: 'number',
        defaultValue: 128,
        editable: true,
    },
    {
        name: 'MAX_NODE_NUM',
        label: 'Max # of Nodes',
        type: 'number',
        defaultValue: 1024,
        editable: true,
    },
    {
        name: 'GENOME_LENGTH',
        label: 'Node\'s Genome Length',
        type: 'number',
        defaultValue: 64,
        editable: true,
    },
    {
        name: 'MUTATION_RATE',
        label: 'Mutation Rate',
        type: 'percent',
        defaultValue: 0.05,
    },
    {
        name: 'NODE_MAX_AGE',
        label: 'Node\'s Max Age',
        type: 'number',
        defaultValue: 512,
        editable: true,
    },
    {
        name: 'NODE_MAX_ENERGY',
        label: 'Node\'s Max Energy',
        type: 'number',
        defaultValue: 256,
        editable: true,
    },
    {
        name: 'NODE_MAX_MINERALS',
        label: 'Node\'s Max Minerals',
        type: 'number',
        defaultValue: 16,
        editable: true,
    },
    {
        name: 'MINERAL_ENERGY',
        label: 'Energy of One Mineral',
        type: 'number',
        defaultValue: 4,
        editable: true,
    },
    {
        name: 'NODE_START_ENERGY',
        label: 'Spawned Node\'s Energy',
        type: 'number',
        defaultValue: 100,
        editable: true,
    },
    {
        name: 'SUN_AMOUNT',
        label: 'Sun Amount',
        type: 'number',
        defaultValue: 10,
        editable: true,
    },
    {
        name: 'SUN_LEVEL_HEIGHT',
        label: 'Sun Level Height',
        type: 'number',
        defaultValue: 4,
        editable: true,
    },
    {
        name: 'MINERAL_AMOUNT',
        label: 'Mineral Amount',
        type: 'number',
        defaultValue: 4,
        editable: true,
    },
    {
        name: 'MINERAL_LEVEL_HEIGHT',
        label: 'Mineral Level Height',
        type: 'number',
        defaultValue: 16,
        editable: true,
    },
    {
        name: 'REPRODUCTION_COST',
        label: 'Energy Amount to Reproduce',
        type: 'number',
        defaultValue: 20,
        editable: true,
    },
    {
        name: 'DEAD_NODE_ENERGY',
        label: 'Energy of a Dead Node',
        type: 'number',
        defaultValue: 20,
        editable: true,
    },
    {
        name: 'SPAWN_RANDOM_NODES',
        label: 'Spawn random nodes',
        type: 'checkbox',
        defaultValue: false,
        editable: true,
    },
    {
        name: 'STARTING_GENOME',
        label: 'Starting Genome',
        type: 'genome',
        defaultValue: [],
    },
    {
        name: 'RELATIVE_THRESHOLD',
        label: 'Relative Threshold',
        type: 'number',
        defaultValue: 2,
        editable: true,
    },
];
