export default [
    {
        name: 'MUTATION_RATE',
        label: 'Mutation Rate',
        type: 'percent',
        defaultValue: 0.25,
        editable: true,
    },
    {
        name: 'NODE_MAX_AGE',
        label: 'Node\'s Max Age',
        type: 'number',
        defaultValue: 511,
        editable: true,
    },
    {
        name: 'NODE_MAX_ENERGY',
        label: 'Node\'s Max Energy',
        type: 'number',
        defaultValue: 255,
        editable: true,
    },
    {
        name: 'NODE_MAX_MINERALS',
        label: 'Node\'s Max Minerals',
        type: 'number',
        defaultValue: 8,
        editable: true,
    },
    {
        name: 'MINERAL_ENERGY',
        label: 'Energy of One Mineral',
        type: 'number',
        defaultValue: 2,
        editable: true,
    },
    {
        name: 'SUN_AMOUNT',
        label: 'Sun Amount',
        type: 'number',
        defaultValue: 20,
        editable: true,
    },
    {
        name: 'SUN_LEVEL_HEIGHT',
        label: 'Sun Level Height',
        type: 'number',
        defaultValue: 2,
        editable: true,
    },
    {
        name: 'MINERAL_AMOUNT',
        label: 'Mineral Amount',
        type: 'number',
        defaultValue: 4,
        editable: true,
    },
    {
        name: 'MINERAL_LEVEL_HEIGHT',
        label: 'Mineral Level Height',
        type: 'number',
        defaultValue: 16,
        editable: true,
    },
    {
        name: 'REPRODUCTION_COST',
        label: 'Energy Amount to Reproduce',
        type: 'number',
        defaultValue: 150,
        editable: true,
    },
    {
        name: 'DEAD_NODE_ENERGY',
        label: 'Energy of a Dead Node',
        type: 'number',
        defaultValue: 20,
        editable: true,
    },
    {
        name: 'RELATIVE_THRESHOLD',
        label: 'Relative Threshold',
        type: 'number',
        defaultValue: 1,
        editable: true,
    },
    {
        name: 'PREDATOR_DEFENSE',
        label: 'Predator Defense',
        type: 'percent',
        defaultValue: 0.1,
        editable: true,
    },
    {
        name: 'FOOD_GROUND_LEVEL',
        label: 'Food Ground Level',
        type: 'number',
        defaultValue: 57,
        editable: true,
    },
];
